#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x42C9C8D3AF5EA5E3 (agaida@siduction.org)
#
Name     : lxqt-openssh-askpass
Version  : 0.14.1
Release  : 4
URL      : https://github.com/lxqt/lxqt-openssh-askpass/releases/download/0.14.1/lxqt-openssh-askpass-0.14.1.tar.xz
Source0  : https://github.com/lxqt/lxqt-openssh-askpass/releases/download/0.14.1/lxqt-openssh-askpass-0.14.1.tar.xz
Source1  : https://github.com/lxqt/lxqt-openssh-askpass/releases/download/0.14.1/lxqt-openssh-askpass-0.14.1.tar.xz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.1
Requires: lxqt-openssh-askpass-bin = %{version}-%{release}
Requires: lxqt-openssh-askpass-data = %{version}-%{release}
Requires: lxqt-openssh-askpass-license = %{version}-%{release}
Requires: lxqt-openssh-askpass-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : liblxqt-data
BuildRequires : liblxqt-dev
BuildRequires : lxqt-build-tools
BuildRequires : qtbase-dev
BuildRequires : qttools-dev

%description
# lxqt-openssh-askpass
## Overview
`lxqt-openssh-askpass` is a GUI to query credentials on behalf of other programs.
As indicated by its name it's primarily targeted at `ssh-agent`, the SSH agent
of OpenSSH, but it works with other applications like e. g. EncFS as well.

%package bin
Summary: bin components for the lxqt-openssh-askpass package.
Group: Binaries
Requires: lxqt-openssh-askpass-data = %{version}-%{release}
Requires: lxqt-openssh-askpass-license = %{version}-%{release}

%description bin
bin components for the lxqt-openssh-askpass package.


%package data
Summary: data components for the lxqt-openssh-askpass package.
Group: Data

%description data
data components for the lxqt-openssh-askpass package.


%package license
Summary: license components for the lxqt-openssh-askpass package.
Group: Default

%description license
license components for the lxqt-openssh-askpass package.


%package man
Summary: man components for the lxqt-openssh-askpass package.
Group: Default

%description man
man components for the lxqt-openssh-askpass package.


%prep
%setup -q -n lxqt-openssh-askpass-0.14.1
cd %{_builddir}/lxqt-openssh-askpass-0.14.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1598295358
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1598295358
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/lxqt-openssh-askpass
cp %{_builddir}/lxqt-openssh-askpass-0.14.1/LICENSE %{buildroot}/usr/share/package-licenses/lxqt-openssh-askpass/7fab4cd4eb7f499d60fe183607f046484acd6e2d
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/lxqt-openssh-askpass

%files data
%defattr(-,root,root,-)
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_ar.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_ca.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_cs.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_cy.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_da.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_de.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_el.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_es.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_fr.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_gl.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_he.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_hu.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_id.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_it.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_ja.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_lt.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_nb_NO.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_nl.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_pl.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_pt.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_ru.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_tr.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_uk.qm
/usr/share/lxqt/translations/lxqt-openssh-askpass/lxqt-openssh-askpass_zh_CN.qm

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/lxqt-openssh-askpass/7fab4cd4eb7f499d60fe183607f046484acd6e2d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/lxqt-openssh-askpass.1
